a = "WELCOME TO FINANCE GEEK HUB"
print(a.center(183))
print("\n")
print("OPTIONS: asset, liability, net worth, income, expenses, budget, cash flow, interest, compound interest, credit score, loan, equity, investment, diversification, return on investment,  bonds, balance sheet, capital gain, liquidity")
print("\n")
# Ask the user for input
terminology = input("What's your query:")
print("\n")
#Simple if-else logic to check the answer
if terminology == "asset":
    print("An asset is something you own that adds financial value or helps you generate it.")    
elif terminology == "liability":
    print("A liability is something that a person or company owes, usually a sum of money. Liabilities are settled over time through the transfer of economic benefits including money, goods, or services.")        
elif terminology == "income":
    print("The term income refers to any type of compensation or benefit received in exchange for work performed or for capital invested.")    
elif terminology == "budget":
    print("A budget is estimation that's made for a specified future period of time.")
elif terminology == "diversification":
    print("Diversification is a risk management strategy that creates a mix of various investments within a portfolio.")    
elif terminology == "cash flow":
    print("Cash flow is the movement of money into and out of a company over a certain period of time.")
elif terminology == "capital gain":
    print("A capital gain refers to the increase in the value of a capital asset that is realized when it's sold.")    
elif terminology == "interest":
    print("Interest is the charge for borrowing money.")
elif terminology == "bonds":
    print("A bond, which is offered by most brokerage platforms, is a fixed-income investment product where individuals lend money to a government or company at a specified interest rate for a predetermined period.")    
elif terminology == "compound interest":
    print("Compound interest is interest that is added to the initial principal of an investment or loan, thereby increasing the balance and, in turn, increasing the amount of interest earned or paid in the next period.")
elif terminology == "credit score":
    print("A credit score is a three-digit number that rates an individual's credit worthiness and ability to obtain a loan, mortgage, or credit card.")
elif terminology == "loan":
    print("A loan is a form of credit where a specific amount of money is given to someone with the agreement that it will be paid back later.")
elif terminology == "equity":
    print("In finance, equity refers to an ownership stake whose value is reduced by an associated debt.")
elif terminology == "expenses":
    print("Expenses for a company are generally categorized as operating or nonoperating expenses. They’re every cost that a business runs into to produce income.")    
elif terminology == "investment":
    print("An investment is an asset or property acquired to generate income or gain appreciation.")
elif terminology == "return on investment":
    print("Expressed as a percentage, return on investment (ROI) is a financial ratio that measures the profit generated by an investment relative to its cost.")
elif terminology == "balance sheet":
    print("A balance sheet is a financial statement that shows what a company owns, what it owes, and the amount invested by shareholders at a specific point in time.")
elif terminology == "liquidity":
    print("When an asset can be efficiently converted into ready cash without affecting its market value, it is considered a liquid asset.")
elif terminology == "net worth":
    print("Net worth is the difference between what a person or company owns and what they owe.")    
else:
    print("There will be an update for this term soon!")
print("\n")    
#End saying to the user
x = "THANK YOU SO MUCH!!!"
print(x.center(182))
